// Copyright 2020 Kulandin Denis
#include <bits/stdc++.h>
using namespace std;
int main() {
    map<string, string> mp;
    mp["AAA"] = "K";
    mp["AAC"] = "N";
    mp["AAG"] = "K";
    mp["AAU"] = "N";
    mp["ACA"] = "T";
    mp["ACC"] = "T";
    mp["ACG"] = "T";
    mp["ACU"] = "T";
    mp["AGA"] = "R";
    mp["AGC"] = "S";
    mp["AGG"] = "R";
    mp["AGU"] = "S";
    mp["AUA"] = "I";
    mp["AUC"] = "I";
    mp["AUG"] = "M";
    mp["AUU"] = "I";
    mp["CAA"] = "Q";
    mp["CAC"] = "H";
    mp["CAG"] = "Q";
    mp["CAU"] = "H";
    mp["CCA"] = "P";
    mp["CCC"] = "P";
    mp["CCG"] = "P";
    mp["CCU"] = "P";
    mp["CGA"] = "R";
    mp["CGC"] = "R";
    mp["CGG"] = "R";
    mp["CGU"] = "R";
    mp["CUA"] = "L";
    mp["CUC"] = "L";
    mp["CUG"] = "L";
    mp["CUU"] = "L";
    mp["GAA"] = "E";
    mp["GAC"] = "D";
    mp["GAG"] = "E";
    mp["GAU"] = "D";
    mp["GCA"] = "A";
    mp["GCC"] = "A";
    mp["GCG"] = "A";
    mp["GCU"] = "A";
    mp["GGA"] = "G";
    mp["GGC"] = "G";
    mp["GGG"] = "G";
    mp["GGU"] = "G";
    mp["GUA"] = "V";
    mp["GUC"] = "V";
    mp["GUG"] = "V";
    mp["GUU"] = "V";
    mp["UAA"] = "STOP";
    mp["UAC"] = "Y";
    mp["UAG"] = "STOP";
    mp["UAU"] = "Y";
    mp["UCA"] = "S";
    mp["UCC"] = "S";
    mp["UCG"] = "S";
    mp["UCU"] = "S";
    mp["UGA"] = "STOP";
    mp["UGC"] = "C";
    mp["UGG"] = "W";
    mp["UGU"] = "C";
    mp["UUA"] = "L";
    mp["UUC"] = "F";
    mp["UUG"] = "L";
    mp["UUU"] = "F";
    string s;
    cin >> s;
    string ans;
    for(int i = 0;i < s.size();i += 3){
        string t = s.substr(i, 3);
        t = mp[t];
        if (t == "STOP") break;
        ans += t;
    }
    cout << ans << '\n';
    return 0;
}